packages:
  - core

allowBuilds:
  '@google/genai': false
  '@nkzw/mdx-editor': true
  '@swc/core': true
  electron: true
  electron-winstaller: true
  protobufjs: false
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - '@nkzw/*'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.4f61f920640a17d1ebd019f516e883f6de6a9811
  vite-plus: 0.0.0-commit.4f61f920640a17d1ebd019f516e883f6de6a9811
  vitest: 4.1.9
nodeLinker: hoisted
onlyBuiltDependencies:
  - '@nkzw/mdx-editor'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - electron
  - electron-winstaller
  - unrs-resolver
overrides:
  extract-zip>yauzl: ^3.4.0
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
