packages:
  - core

allowBuilds:
  '@google/genai': false
  '@swc/core': true
  electron: true
  electron-winstaller: true
  protobufjs: false
blockExoticSubdeps: false
catalog:
  vite: https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1856
  vite-plus: https://pkg.pr.new/voidzero-dev/vite-plus@1856
  vitest: 4.1.9
nodeLinker: hoisted
minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - '@voidzero-dev/*'
  - vite-plus
  - '@vitest/*'
  - vite
  - vitest
  - '@oxc-project/*'
  - '@oxlint/*'
  - oxlint
  - oxfmt
  - oxlint-tsgolint
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - electron
  - electron-winstaller
  - unrs-resolver
overrides:
  extract-zip>yauzl: ^3.4.0
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
